In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
xls = pd.ExcelFile('../dataset/hr_dataset.xlsx')

xls.sheet_names

['Employees', 'Departments', 'Locations', 'Jobs', 'Attendance', 'Attrition']

In [25]:
len(xls.sheet_names)

6

In [6]:
employees = pd.read_excel('../dataset/hr_dataset.xlsx',sheet_name='Employees')
departments = pd.read_excel('../dataset/hr_dataset.xlsx',sheet_name='Departments')
locations = pd.read_excel('../dataset/hr_dataset.xlsx',sheet_name='Locations')
jobs = pd.read_excel('../dataset/hr_dataset.xlsx',sheet_name='Jobs')
attendance = pd.read_excel('../dataset/hr_dataset.xlsx',sheet_name='Attendance')
attrition = pd.read_excel('../dataset/hr_dataset.xlsx',sheet_name='Attrition')

In [7]:
employees.head()

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,PerformanceRating,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,1,8,5,24,90.3,3.4,0,46893,19
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,1,8,8,13,78.5,3.2,1,50055,23
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,1,2,0,0,65.3,2.8,5,80027,14
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,1,5,1,32,69.3,3.7,6,967,12
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,4,1,6,6,76.5,3.1,4,38246,10

In [8]:
departments.head()

   DeptID Department  Budget_USD  Headcount_Target
0       1         HR      300000                25
1       2    Finance      500000                30
2       3         IT      900000                60
3       4      Sales      700000                55
4       5  Marketing      450000                28

In [9]:
locations.head()

   LocationID     City      State Region
0           1    Noida         UP  North
1           2  Lucknow         UP  North
2           3    Delhi      Delhi  North
3           4   Jaipur  Rajasthan   West

In [10]:
jobs.head()

   JobID    JobTitle Grade  BaseSalaryBand
0      1     Analyst    G4          600000
1      2     Manager    G7         1200000
2      3   Executive    G3          450000
3      4    Engineer    G5          900000
4      5  Specialist    G5          800000

In [11]:
attendance.head()

   EmployeeID  DaysPresent  LeavesTaken  WFHDays  LateMarks
0           1          205           10        7          6
1           2          252            7       15          8
2           3          223            8       15         11
3           4          242           14        5         11
4           5          225            5        4         11

In [12]:
attrition.head()

   EmployeeID      ExitReason  NoticePeriodDays
0          14      Relocation                59
1          15      Relocation                15
2          17             Pay                20
3          35      Relocation                90
4          37  Higher Studies                 5

<h2>Shape of the dataframes</h2>

In [13]:
employees.shape

(230, 19)

In [14]:
departments.shape

(6, 4)

In [15]:
locations.shape

(4, 4)

In [16]:
jobs.shape

(8, 4)

In [17]:
attendance.shape

(230, 5)

In [18]:
attrition.shape

(42, 3)

<h2>Information of Dataframes</h2>

In [19]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           230 non-null    int64
 1   EmpCode              230 non-null    str
 2   DeptID               230 non-null    int64
 3   LocationID           230 non-null    int64
 4   JobID                230 non-null    int64
 5   HireDate             230 non-null    datetime64[us]
 6   Age                  230 non-null    int64
 7   Gender               230 non-null    str
 8   EmploymentStatus     230 non-null    str
 9   Salary               230 non-null    int64
 10  PerformanceRating    230 non-null    int64
 11  TrainingHours        230 non-null    int64
 12  AbsenteeismDays      230 non-null    int64
 13  OvertimeHours        230 non-null    int64
 14  EngagementScore      230 non-null    float64
 15  SatisfactionScore    230 non-null    float64
 16  YearsSincePromotion  230 non-null    int64
 17  Bonus                230 non-null    int64
 18  ManagerID            230 non-null    int64
dtypes: datetime64[us](1), float64(2), int64(13), str(3)
memory usage: 34.3 KB

In [20]:
departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DeptID            6 non-null      int64
 1   Department        6 non-null      str
 2   Budget_USD        6 non-null      int64
 3   Headcount_Target  6 non-null      int64
dtypes: int64(3), str(1)
memory usage: 324.0 bytes

In [21]:
jobs.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   JobID           8 non-null      int64
 1   JobTitle        8 non-null      str
 2   Grade           8 non-null      str
 3   BaseSalaryBand  8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

In [22]:
locations.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LocationID  4 non-null      int64
 1   City        4 non-null      str
 2   State       4 non-null      str
 3   Region      4 non-null      str
dtypes: int64(1), str(3)
memory usage: 260.0 bytes

In [23]:
attendance.info()

<class 'pandas.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   230 non-null    int64
 1   DaysPresent  230 non-null    int64
 2   LeavesTaken  230 non-null    int64
 3   WFHDays      230 non-null    int64
 4   LateMarks    230 non-null    int64
dtypes: int64(5)
memory usage: 9.1 KB

In [24]:
attrition.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        42 non-null     int64
 1   ExitReason        42 non-null     str
 2   NoticePeriodDays  42 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.1 KB

<h2>Merge all sheets</h2>

In [27]:
df = employees.merge(departments,on='DeptID',how='left') \
              .merge(locations,on='LocationID',how='left') \
              .merge(jobs,on='JobID',how='left') \
              .merge(attendance,on='EmployeeID',how='left') \
              .merge(attrition,on='EmployeeID',how='left')

In [29]:
df.shape

(230, 34)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           230 non-null    int64
 1   EmpCode              230 non-null    str
 2   DeptID               230 non-null    int64
 3   LocationID           230 non-null    int64
 4   JobID                230 non-null    int64
 5   HireDate             230 non-null    datetime64[us]
 6   Age                  230 non-null    int64
 7   Gender               230 non-null    str
 8   EmploymentStatus     230 non-null    str
 9   Salary               230 non-null    int64
 10  PerformanceRating    230 non-null    int64
 11  TrainingHours        230 non-null    int64
 12  AbsenteeismDays      230 non-null    int64
 13  OvertimeHours        230 non-null    int64
 14  EngagementScore      230 non-null    float64
 15  SatisfactionScore    230 non-null    float64
 16  YearsSincePromotion  230 non-null    int64
 17  Bonus                230 non-null    int64
 18  ManagerID            230 non-null    int64
 19  Department           230 non-null    str
 20  Budget_USD           230 non-null    int64
 21  Headcount_Target     230 non-null    int64
 22  City                 230 non-null    str
 23  State                230 non-null    str
 24  Region               230 non-null    str
 25  JobTitle             230 non-null    str
 26  Grade                230 non-null    str
 27  BaseSalaryBand       230 non-null    int64
 28  DaysPresent          230 non-null    int64
 29  LeavesTaken          230 non-null    int64
 30  WFHDays              230 non-null    int64
 31  LateMarks            230 non-null    int64
 32  ExitReason           42 non-null     str
 33  NoticePeriodDays     42 non-null     float64
dtypes: datetime64[us](1), float64(3), int64(20), str(10)
memory usage: 61.2 KB

In [31]:
df.isnull().sum()

EmployeeID               0
EmpCode                  0
DeptID                   0
LocationID               0
JobID                    0
HireDate                 0
Age                      0
Gender                   0
EmploymentStatus         0
Salary                   0
PerformanceRating        0
TrainingHours            0
AbsenteeismDays          0
OvertimeHours            0
EngagementScore          0
SatisfactionScore        0
YearsSincePromotion      0
Bonus                    0
ManagerID                0
Department               0
Budget_USD               0
Headcount_Target         0
City                     0
State                    0
Region                   0
JobTitle                 0
Grade                    0
BaseSalaryBand           0
DaysPresent              0
LeavesTaken              0
WFHDays                  0
LateMarks                0
ExitReason             188
NoticePeriodDays       188
dtype: int64

In [35]:
df.isnull().sum() / len(df) * 100

EmployeeID             0.0
EmpCode                0.0
DeptID                 0.0
LocationID             0.0
JobID                  0.0
HireDate               0.0
Age                    0.0
Gender                 0.0
EmploymentStatus       0.0
Salary                 0.0
PerformanceRating      0.0
TrainingHours          0.0
AbsenteeismDays        0.0
OvertimeHours          0.0
EngagementScore        0.0
SatisfactionScore      0.0
YearsSincePromotion    0.0
Bonus                  0.0
ManagerID              0.0
Department             0.0
Budget_USD             0.0
Headcount_Target       0.0
City                   0.0
State                  0.0
Region                 0.0
JobTitle               0.0
Grade                  0.0
BaseSalaryBand         0.0
DaysPresent            0.0
LeavesTaken            0.0
WFHDays                0.0
LateMarks              0.0
ExitReason             0.0
NoticePeriodDays       0.0
dtype: float64

In [34]:
df['ExitReason'] = df['ExitReason'].fillna('Active')
df['NoticePeriodDays'] = df['NoticePeriodDays'].fillna(0)

In [38]:
len(df[df['ExitReason']!='Active'])/len(df)*100

18.26086956521739

<h2>Key Metrics</h2>

In [39]:
metrics = {
    'Total Employees': len(df),
    'Average Salary' : df['Salary'].mean(),
    'Attrition Rate (%)' : len(df[df['ExitReason']!='Active'])/len(df)*100,
    'Avg Engagement Score': df['EngagementScore'].mean(),
    'Avg Satisfaction Score': df['SatisfactionScore'].mean(),
    'Total Bonus Pool' : df['Bonus'].sum(),
    'Avg Training hours' : df['TrainingHours'].mean(),
    'Avg Age': df['Age'].mean(),
    'Total Departments': df['Department'].nunique(),
    'Avg year since Promotion': df['YearsSincePromotion'].mean()   
    }

In [41]:
for k,v in metrics.items():
    print(f"{k}: {v:,.2f}")

Total Employees: 230.00
Average Salary: 718,704.14
Attrition Rate (%): 18.26
Avg Engagement Score: 72.65
Avg Satisfaction Score: 3.56
Total Bonus Pool: 13,899,026.00
Avg Training hours: 4.27
Avg Age: 39.98
Total Departments: 6.00
Avg year since Promotion: 2.94

<h2>Insights</h2>

1. Group by salary by department

In [51]:
df.groupby('Department')['Salary'].mean()

Department
Finance       662001.100000
HR            718069.857143
IT            771028.727273
Marketing     723665.564103
Operations    689802.411765
Sales         710298.750000
Name: Salary, dtype: float64

Highest avg salary department Label

In [50]:
df.groupby('Department')['Salary'].mean().idxmax()

'IT'

Lowest avg salary department Label

In [49]:
df.groupby('Department')['Salary'].mean().idxmin()

'Finance'

In [52]:
df.groupby('Department')['Salary'].sum()

Department
Finance       19860033
HR            20105956
IT            42406580
Marketing     28222957
Operations    23453282
Sales         31253145
Name: Salary, dtype: int64

2. Gender Distribution

In [66]:
print(f"Male: {(df['Gender']=='Male').mean()*100:,.2f}")
print(f"Female: {(df['Gender']=='Female').mean()*100:,.2f}")

Male: 53.91
Female: 46.09