<center><h1 style="color:teal;"><strong>Handling Missing values</strong></h1></center>

<h3><strong>What is missing Values?</strong></h3>

Missing values (often presented as NaN,null,none) occur when no data value is stored for a variable in observation.

<h3><strong>Why does missing data occur?</strong></h3>

- Data entry error: Human oversight during manual input.
- Equipment Malfunction: Sensors failling or losing connectivity
- Non-Response: In surveys, people might feel uncomfortable answering questions, Income , health, or weight etc.
- Data Integration Issues: Merging two databases where one lacks a column present in the other

<h3><strong>Impact on ML Models</strong></h3>

Most scikit learn algorithms can not handle missing values and will throw an error.

<strong>Ignoring the problem leads to:</strong>

- Bias: If the data is missing for specific reason, deleting it changes the TRUTH of your dataset.
- Loss of Power: Reduced sample size leads to less reliable models.

<h3><strong>Types of Missing Data</strong></h3>

1. MCAR(Missing Completely at Random): There probability of being missing is the same for all observations. there is no relationship between the missing data and any other values.
2. MAR(Missing at Random): The missingness is related to observed data. but not the missing values themselves.
3. MNAR(Missing Not at Random): The missingness depends on the unobserved value itself. This is hardest to handle.

<h3><strong>Ways to handle Missing values</strong></h3>

1. Remove Them (Rows,columns)
2. Impute

<h2><strong>Imputation</strong></h2>

1. Univariate(Numerical Data, Categorical Data)
2. Multivariate(KNN Imputation,Iterative Imputation)

<center><h3 style="color:Green;"><strong>Remove Them</strong></h3></center>

<h3><strong >Removing the rows</strong>

Row deletion, Known as <strong>listwise deletion</strong>, means that if a single "cell" in a row is NaN, the entire record is going to removed from dataset.

<strong>When it is GOOD to use</strong>

- Low Percentage: if < 5% of you data is missing.
- MCAR: The missingness has no hidden pattern.
- Large Datasets: If you have millions of rows, losing 100 won't hurt your model's performance.

<strong>When it is NOT recommended</storng>

- Small datasets: If only 100 rows, every singel row is precious.
- Bias risk: If only "High income" individuals refused to answer the survey, dropping thos rows , removes you "High income" represntation entirely.

In [1]:
import pandas as pd
import numpy as np


data = {
    "Name":["A","B","C","D","E","F"],
    "Age":[25,np.nan,30,35,np.nan,40],
    "Score":[85,90,np.nan,88,92,95],
    "Attendance":[100,90,80,np.nan,90,85]
}

df = pd.DataFrame(data)

In [2]:
df

  Name   Age  Score  Attendance
0    A  25.0   85.0       100.0
1    B   NaN   90.0        90.0
2    C  30.0    NaN        80.0
3    D  35.0   88.0         NaN
4    E   NaN   92.0        90.0
5    F  40.0   95.0        85.0

In [3]:
df_dropped = df.dropna()
print(df_dropped)

  Name   Age  Score  Attendance
0    A  25.0   85.0       100.0
5    F  40.0   95.0        85.0

In [4]:
df_subset = df.dropna(subset=['Age','Score'])
print(df_subset)

  Name   Age  Score  Attendance
0    A  25.0   85.0       100.0
3    D  35.0   88.0         NaN
5    F  40.0   95.0        85.0

In [12]:
df_thresh = df.dropna(thresh=4)#if you are having atleast n(threshold) non-NaN values
print(df_thresh)

  Name   Age  Score  Attendance
0    A  25.0   85.0       100.0
5    F  40.0   95.0        85.0

<h3><strong>Removing the columns</strong></h3>

Columns deletion involves removing an entire variable from the dataset:

Imapact: You are reducing you feature space(Dimensionality).

<strong>When it is GOOD to use</strong>

- High missingness: If column is missing >50% of its values. 
- Irrelvance: If the feature is not crucial for the prediction.


<strong>When It is not Recommended</strong>

- Domain Importance: If it crucial for rest of the features.

In [13]:
df["Notes"] = [np.nan,"Good",np.nan,np.nan,np.nan,"Average"]

In [14]:
df

  Name   Age  Score  Attendance    Notes
0    A  25.0   85.0       100.0      NaN
1    B   NaN   90.0        90.0     Good
2    C  30.0    NaN        80.0      NaN
3    D  35.0   88.0         NaN      NaN
4    E   NaN   92.0        90.0      NaN
5    F  40.0   95.0        85.0  Average

In [18]:
missing_pct = df.isnull().sum() / len(df) *100

In [20]:
limit = 50
cols_to_drop = missing_pct[missing_pct>50].index
df_reduced = df.drop(columns=cols_to_drop)

In [21]:
df_reduced

  Name   Age  Score  Attendance
0    A  25.0   85.0       100.0
1    B   NaN   90.0        90.0
2    C  30.0    NaN        80.0
3    D  35.0   88.0         NaN
4    E   NaN   92.0        90.0
5    F  40.0   95.0        85.0