In [44]:
import numpy as np
import pandas as pd

np.random.seed(42)

n = 100

data = pd.DataFrame({
    'age':np.random.randint(18,60,n),
    "salary":np.random.randint(20000,100000,n),
    "ciyt":np.random.choice(['Delhi','Mumbai','Pune'],n),
    "gender":np.random.choice(['Male','Female'],n),
    "purchased":np.random.choice([0,1],n)
})

data.head()

   age  salary   ciyt  gender  purchased
0   56   28392   Pune    Male          0
1   46   50535   Pune  Female          0
2   32   98603   Pune    Male          1
3   25   72256  Delhi  Female          1
4   38   55222  Delhi    Male          0

<h2>Feature Construction</h2>
Feature construction is the process of creating new features from existing data to improve model performance.

In [11]:
data['salary_per_age'] = data['salary']/data['age']

In [5]:
data.head()

   age  salary   ciyt  gender  purchased  salary_per_age Age_group
0   56   28392   Pune    Male          0      507.000000    Senior
1   46   50535   Pune  Female          0     1098.586957    Senior
2   32   98603   Pune    Male          1     3081.343750       Mid
3   25   72256  Delhi  Female          1     2890.240000     Young
4   38   55222  Delhi    Male          0     1453.210526       Mid

In [12]:
data['Age_group'] = pd.cut(data['age'],bins=[18,30,45,60],labels=['Young','Mid','Senior'])

<h2>Feature Scaling</h2>

Transforming features so they are on similar scale

- Distance based models it is necessary
- Prevent feature dominance

StandardScaler(z-score)

z = (x - mean)/std

Inverse = (z x std + mean)

In [17]:
data['age'].mean()

np.float64(37.91)

In [19]:
data['age'].std()

np.float64(12.219453772777674)

In [22]:
data['manual_scaled']=(data['age']-data['age'].mean())/data['age'].std()

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data[['Age_scaled','salary_scaled']] = scaler.fit_transform(data[['age','salary']])

In [23]:
data.head()

,age,salary,ciyt,gender,purchased,salary_per_age,Age_group,Age_scaled,salary_scaled,salary_scaled_min_max,manual_scaled
0,56,28392,Pune,Male,0,507.000000,Senior,1.487884,-1.491219,0.103139,1.480426
1,46,50535,Pune,Female,0,1098.586957,Senior,0.665394,-0.506342,0.382127,0.662059
2,32,98603,Pune,Male,1,3081.343750,Mid,-0.486092,1.631629,0.987753,-0.483655
3,25,72256,Delhi,Female,1,2890.240000,Young,-1.061835,0.459766,0.655798,-1.056512
4,38,55222,Delhi,Male,0,1453.210526,Mid,0.007402,-0.297873,0.441180,0.007365

X = (x-min) / (max - min)

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data[['salary_scaled_min_max']] = scaler.fit_transform(data[['salary']])

In [24]:
data['manual_min_max_salary'] = (data['salary'] - data['salary'].min())/(data['salary'].max()-data['salary'].min())

In [25]:
data.head()

,age,salary,ciyt,gender,purchased,salary_per_age,Age_group,Age_scaled,salary_scaled,salary_scaled_min_max,manual_scaled,manual_min_max_salary
0,56,28392,Pune,Male,0,507.000000,Senior,1.487884,-1.491219,0.103139,1.480426,0.103139
1,46,50535,Pune,Female,0,1098.586957,Senior,0.665394,-0.506342,0.382127,0.662059,0.382127
2,32,98603,Pune,Male,1,3081.343750,Mid,-0.486092,1.631629,0.987753,-0.483655,0.987753
3,25,72256,Delhi,Female,1,2890.240000,Young,-1.061835,0.459766,0.655798,-1.056512,0.655798
4,38,55222,Delhi,Male,0,1453.210526,Mid,0.007402,-0.297873,0.441180,0.007365,0.441180

Inverse scaled

In [29]:
data

    age  salary    ciyt  gender  purchased
0    56   28392    Pune    Male          0
1    46   50535    Pune  Female          0
2    32   98603    Pune    Male          1
3    25   72256   Delhi  Female          1
4    38   55222   Delhi    Male          0
..  ...     ...     ...     ...        ...
95   59   69811   Delhi  Female          1
96   56   22811   Delhi    Male          0
97   58   76250  Mumbai  Female          1
98   45   92082   Delhi  Female          1
99   24   54754    Pune  Female          1

[100 rows x 5 columns]

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled = scaler.fit_transform(data[['age','salary']])

data[['age_scaled','salary_scaled']] = scaled

In [46]:

original = scaler.inverse_transform(scaled)

data[['age_original','salary_original']] = original

In [47]:
data

,age,salary,ciyt,gender,purchased,age_scaled,salary_scaled,age_original,salary_original
0,56,28392,Pune,Male,0,1.487884,-1.491219,56.0,28392.0
1,46,50535,Pune,Female,0,0.665394,-0.506342,46.0,50535.0
2,32,98603,Pune,Male,1,-0.486092,1.631629,32.0,98603.0
3,25,72256,Delhi,Female,1,-1.061835,0.459766,25.0,72256.0
4,38,55222,Delhi,Male,0,0.007402,-0.297873,38.0,55222.0
...,...,...,...,...,...,...,...,...,...
95,59,69811,Delhi,Female,1,1.734631,0.351017,59.0,69811.0
96,56,22811,Delhi,Male,0,1.487884,-1.739451,56.0,22811.0
97,58,76250,Mumbai,Female,1,1.652382,0.637411,58.0,76250.0
98,45,92082,Delhi,Female,1,0.583145,1.341587,45.0,92082.0
99,24,54754,Pune,Female,1,-1.144084,-0.318689,24.0,54754.0

In [48]:
data['salary_manual_invers'] = (data['salary_scaled']*data['salary'].std()) + data['salary'].mean()

In [49]:
data

,age,salary,ciyt,gender,purchased,age_scaled,salary_scaled,age_original,salary_original,salary_manual_invers
0,56,28392,Pune,Male,0,1.487884,-1.491219,56.0,28392.0,28223.096714
1,46,50535,Pune,Female,0,0.665394,-0.506342,46.0,50535.0,50477.649058
2,32,98603,Pune,Male,1,-0.486092,1.631629,32.0,98603.0,98787.806762
3,25,72256,Delhi,Female,1,-1.061835,0.459766,25.0,72256.0,72308.075443
4,38,55222,Delhi,Male,0,0.007402,-0.297873,38.0,55222.0,55188.261298
...,...,...,...,...,...,...,...,...,...,...
95,59,69811,Delhi,Female,1,1.734631,0.351017,59.0,69811.0,69850.757985
96,56,22811,Delhi,Male,0,1.487884,-1.739451,56.0,22811.0,22613.980667
97,58,76250,Mumbai,Female,1,1.652382,0.637411,58.0,76250.0,76322.196477
98,45,92082,Delhi,Female,1,0.583145,1.341587,45.0,92082.0,92233.955168
99,24,54754,Pune,Female,1,-1.144084,-0.318689,24.0,54754.0,54717.903600